ARG IMG_VERSION=1
FROM public.ecr.aws/lambda/go:$IMG_VERSION
ARG EXPOSED_PORT=8080
EXPOSE $${EXPOSED_PORT}
ARG LOG_ENABLED=1
# Adding $$ to enable copying the file through terraform templating process.
COPY ${APP_NAME} $${LAMBDA_TASK_ROOT}
ADD config.cfg $${LAMBDA_TASK_ROOT}/config.cfg
ENV TRACE_LOG_UTIL_ENABLE $LOG_ENABLED

CMD [ "${APP_NAME}" ]
